# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aacc461a80a9ebb94c4aa7ca1cb6d77840d1161de86598d3f1e4b3fac34fe7ca225eeb03d45e0cb2b792aed7e54679a08746e5e57581328c0934ff73638f0118

test:
  secret_key_base: 937e01f0f0d02a279ca9cf6b3b250961009154969cebf64e334a368faf6fc83eae037126fe4cd3ea3ee1c6da337999ff4cf50416b9e16e890ae95a736177f9fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
